INFO 2024-03-08 14:58:30,374 autoreload 2208 6860 Watching for file changes with StatReloader
INFO 2024-03-08 14:58:33,173 basehttp 2208 4248 "GET /task05/headtails/ HTTP/1.1" 200 10
INFO 2024-03-08 14:59:24,729 autoreload 2208 6860 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-08 14:59:25,162 autoreload 17856 1960 Watching for file changes with StatReloader
INFO 2024-03-08 14:59:27,866 basehttp 17856 11396 "GET /task05/headtails/ HTTP/1.1" 200 11
INFO 2024-03-08 14:59:49,553 autoreload 17856 1960 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-08 14:59:49,975 autoreload 12880 3956 Watching for file changes with StatReloader
ERROR 2024-03-08 14:59:51,718 log 12880 17928 Internal Server Error: /task05/headtails/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 25, in headtails
    logger.info()
TypeError: Logger.info() missing 1 required positional argument: 'msg'
ERROR 2024-03-08 14:59:51,720 basehttp 12880 17928 "GET /task05/headtails/ HTTP/1.1" 500 65253
INFO 2024-03-08 15:00:05,045 autoreload 12880 3956 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-08 15:00:05,470 autoreload 12076 1084 Watching for file changes with StatReloader
INFO 2024-03-08 15:00:09,803 basehttp 12076 18036 "GET /task05/headtails/ HTTP/1.1" 200 10
INFO 2024-03-08 15:05:05,025 autoreload 12076 1084 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-08 15:05:05,473 autoreload 6860 2208 Watching for file changes with StatReloader
INFO 2024-03-08 15:07:03,817 autoreload 6860 2208 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-08 15:07:04,242 autoreload 644 6540 Watching for file changes with StatReloader
INFO 2024-03-08 15:07:29,763 basehttp 644 684 "GET /task05/dice/ HTTP/1.1" 200 30
INFO 2024-03-08 15:08:03,741 autoreload 644 6540 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-08 15:08:04,175 autoreload 14132 8424 Watching for file changes with StatReloader
INFO 2024-03-08 15:09:56,202 autoreload 14132 8424 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\lessons\settings.py changed, reloading.
INFO 2024-03-08 15:09:56,634 autoreload 11512 17796 Watching for file changes with StatReloader
INFO 2024-03-08 15:10:05,248 views 11512 1976 Dice was tossed
INFO 2024-03-08 15:10:05,249 basehttp 11512 1976 "GET /task05/dice/ HTTP/1.1" 200 30
INFO 2024-03-08 15:10:09,501 views 11512 1976 It's head!
INFO 2024-03-08 15:10:09,502 basehttp 11512 1976 "GET /task05/headtails/ HTTP/1.1" 200 10
INFO 2024-03-08 15:10:10,270 views 11512 1976 It's tails!
INFO 2024-03-08 15:10:10,271 basehttp 11512 1976 "GET /task05/headtails/ HTTP/1.1" 200 11
INFO 2024-03-08 15:10:22,163 views 11512 1976 Dice was tossed
INFO 2024-03-08 15:10:22,164 basehttp 11512 1976 "GET /task05/dice/ HTTP/1.1" 200 30
INFO 2024-03-08 15:11:14,864 autoreload 11512 17796 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-08 15:11:15,292 autoreload 18020 8520 Watching for file changes with StatReloader
INFO 2024-03-08 15:11:16,360 views 18020 4024 Dice was tossed and gave number 3
INFO 2024-03-08 15:11:16,361 basehttp 18020 4024 "GET /task05/dice/ HTTP/1.1" 200 30
INFO 2024-03-08 15:11:16,792 views 18020 4024 Dice was tossed and gave number 2
INFO 2024-03-08 15:11:16,792 basehttp 18020 4024 "GET /task05/dice/ HTTP/1.1" 200 30
INFO 2024-03-08 15:11:17,157 views 18020 4024 Dice was tossed and gave number 1
INFO 2024-03-08 15:11:17,158 basehttp 18020 4024 "GET /task05/dice/ HTTP/1.1" 200 30
INFO 2024-03-08 15:11:56,045 autoreload 18020 8520 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-08 15:11:56,464 autoreload 4976 12896 Watching for file changes with StatReloader
INFO 2024-03-08 15:12:02,031 views 4976 2688 The random number from 0 to 100 is 94
INFO 2024-03-08 15:12:02,032 basehttp 4976 2688 "GET /task05/random/ HTTP/1.1" 200 37
INFO 2024-03-08 15:12:02,293 views 4976 2688 The random number from 0 to 100 is 28
INFO 2024-03-08 15:12:02,293 basehttp 4976 2688 "GET /task05/random/ HTTP/1.1" 200 37
INFO 2024-03-08 15:12:02,511 views 4976 2688 The random number from 0 to 100 is 67
INFO 2024-03-08 15:12:02,512 basehttp 4976 2688 "GET /task05/random/ HTTP/1.1" 200 37
INFO 2024-03-08 15:12:02,686 views 4976 2688 The random number from 0 to 100 is 99
INFO 2024-03-08 15:12:02,686 basehttp 4976 2688 "GET /task05/random/ HTTP/1.1" 200 37
INFO 2024-03-08 15:12:02,901 views 4976 2688 The random number from 0 to 100 is 3
INFO 2024-03-08 15:12:02,901 basehttp 4976 2688 "GET /task05/random/ HTTP/1.1" 200 36
INFO 2024-03-08 15:17:28,680 basehttp 4976 17796 "GET / HTTP/1.1" 200 12
INFO 2024-03-08 15:19:54,696 autoreload 4976 12896 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 15:19:55,151 autoreload 18068 18016 Watching for file changes with StatReloader
INFO 2024-03-08 15:19:58,862 basehttp 18068 4040 "GET / HTTP/1.1" 200 294
INFO 2024-03-08 15:20:31,958 autoreload 18068 18016 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 15:20:32,394 autoreload 11404 8796 Watching for file changes with StatReloader
INFO 2024-03-08 15:21:03,863 autoreload 11404 8796 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 15:21:04,301 autoreload 12896 4976 Watching for file changes with StatReloader
INFO 2024-03-08 15:21:10,730 basehttp 12896 4800 "GET /about HTTP/1.1" 301 0
INFO 2024-03-08 15:21:10,734 basehttp 12896 17764 "GET /about/ HTTP/1.1" 200 396
INFO 2024-03-08 15:22:46,292 autoreload 12896 4976 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 15:22:46,726 autoreload 1108 13900 Watching for file changes with StatReloader
INFO 2024-03-08 15:22:51,254 basehttp 1108 13668 "GET / HTTP/1.1" 200 461
INFO 2024-03-08 15:22:52,769 basehttp 1108 13668 "GET /about/ HTTP/1.1" 200 401
INFO 2024-03-08 15:23:16,258 autoreload 1108 13900 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 15:23:16,686 autoreload 7272 11248 Watching for file changes with StatReloader
INFO 2024-03-08 15:23:19,846 basehttp 7272 18416 "GET /about/ HTTP/1.1" 200 562
INFO 2024-03-08 15:23:21,738 basehttp 7272 18416 "GET / HTTP/1.1" 200 461
INFO 2024-03-08 15:32:37,653 autoreload 7272 11248 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 15:32:38,082 autoreload 3492 16844 Watching for file changes with StatReloader
INFO 2024-03-08 15:32:45,994 views 3492 6816 Index page accessed
INFO 2024-03-08 15:32:45,994 basehttp 3492 6816 "GET / HTTP/1.1" 200 461
INFO 2024-03-08 15:55:34,603 autoreload 824 8936 Watching for file changes with StatReloader
ERROR 2024-03-08 15:55:37,976 log 824 3576 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py", line 11, in index
    template = loader.get_template("templates/index.html")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: templates/index.html
ERROR 2024-03-08 15:55:37,977 basehttp 824 3576 "GET / HTTP/1.1" 500 71413
INFO 2024-03-08 15:56:29,076 autoreload 824 8936 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 15:56:29,508 autoreload 9792 16804 Watching for file changes with StatReloader
INFO 2024-03-08 15:57:31,020 autoreload 9792 16804 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 15:57:31,449 autoreload 17576 16680 Watching for file changes with StatReloader
INFO 2024-03-08 16:01:37,178 autoreload 17576 16680 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 16:01:37,605 autoreload 3536 3484 Watching for file changes with StatReloader
ERROR 2024-03-08 16:01:44,391 log 3536 17660 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py", line 11, in index
    template = loader.get_template("templates/index.html")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: templates/index.html
ERROR 2024-03-08 16:01:44,393 basehttp 3536 17660 "GET / HTTP/1.1" 500 71413
ERROR 2024-03-08 16:01:46,662 log 3536 17660 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py", line 11, in index
    template = loader.get_template("templates/index.html")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: templates/index.html
ERROR 2024-03-08 16:01:46,664 basehttp 3536 17660 "GET / HTTP/1.1" 500 71256
INFO 2024-03-08 16:02:21,683 autoreload 3536 3484 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 16:02:22,119 autoreload 684 2664 Watching for file changes with StatReloader
INFO 2024-03-08 16:02:23,281 views 684 824 Index page accessed
INFO 2024-03-08 16:02:23,282 basehttp 684 824 "GET / HTTP/1.1" 200 456
INFO 2024-03-08 16:02:58,735 autoreload 684 2664 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-08 16:02:59,171 autoreload 17080 13100 Watching for file changes with StatReloader
INFO 2024-03-08 16:03:01,508 views 17080 1776 About page accessed
INFO 2024-03-08 16:03:01,508 basehttp 17080 1776 "GET /about/ HTTP/1.1" 200 493
INFO 2024-03-08 16:03:03,025 views 17080 1776 Index page accessed
INFO 2024-03-08 16:03:03,026 basehttp 17080 1776 "GET / HTTP/1.1" 200 456
INFO 2024-03-08 16:03:03,877 views 17080 1776 About page accessed
INFO 2024-03-08 16:03:03,878 basehttp 17080 1776 "GET /about/ HTTP/1.1" 200 493
INFO 2024-03-08 16:39:16,638 autoreload 18036 6720 Watching for file changes with StatReloader
INFO 2024-03-09 12:42:18,316 autoreload 7776 15840 Watching for file changes with StatReloader
INFO 2024-03-09 12:42:36,409 views 7776 12560 Index page accessed
INFO 2024-03-09 12:42:36,409 basehttp 7776 12560 "GET / HTTP/1.1" 200 456
WARNING 2024-03-09 12:42:36,448 log 7776 12560 Not Found: /favicon.ico
WARNING 2024-03-09 12:42:36,449 basehttp 7776 12560 "GET /favicon.ico HTTP/1.1" 404 2546
INFO 2024-03-09 12:42:44,428 basehttp 7776 12560 "GET /task05/coin HTTP/1.1" 301 0
INFO 2024-03-09 12:42:44,430 views 7776 8088 It's tails!
INFO 2024-03-09 12:42:44,433 basehttp 7776 8088 "GET /task05/coin/ HTTP/1.1" 200 11
INFO 2024-03-09 12:42:47,047 views 7776 8088 It's heads!
INFO 2024-03-09 12:42:47,048 basehttp 7776 8088 "GET /task05/coin/ HTTP/1.1" 200 11
INFO 2024-03-09 12:42:48,647 views 7776 8088 It's tails!
INFO 2024-03-09 12:42:48,648 basehttp 7776 8088 "GET /task05/coin/ HTTP/1.1" 200 11
INFO 2024-03-09 12:51:33,939 autoreload 7776 15840 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 12:51:34,367 autoreload 15948 10576 Watching for file changes with StatReloader
INFO 2024-03-09 12:51:54,509 autoreload 15948 10576 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 12:51:54,937 autoreload 10344 7316 Watching for file changes with StatReloader
INFO 2024-03-09 12:52:09,895 views 10344 5660 It's tails!
ERROR 2024-03-09 12:52:09,933 log 10344 5660 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 33, in coin
    return HttpResponse(template.render(coin_, context))
                        ^^^^^^^^^^^^^^^
AttributeError: module 'django.utils.translation.template' has no attribute 'render'
ERROR 2024-03-09 12:52:09,935 basehttp 10344 5660 "GET /task05/coin/ HTTP/1.1" 500 65961
INFO 2024-03-09 12:52:39,040 autoreload 10344 7316 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 12:52:39,472 autoreload 17812 15092 Watching for file changes with StatReloader
INFO 2024-03-09 12:52:54,393 autoreload 17812 15092 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 12:52:54,820 autoreload 5148 14624 Watching for file changes with StatReloader
INFO 2024-03-09 12:52:59,113 views 5148 4104 It's heads!
ERROR 2024-03-09 12:52:59,144 log 5148 4104 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 35, in coin
    return HttpResponse(template.render(coin_, context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 57, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\context.py", line 286, in make_context
    raise TypeError(
TypeError: context must be a dict rather than str.
ERROR 2024-03-09 12:52:59,146 basehttp 5148 4104 "GET /task05/coin/ HTTP/1.1" 500 74150
INFO 2024-03-09 12:53:23,413 autoreload 5148 14624 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 12:53:23,841 autoreload 7272 18268 Watching for file changes with StatReloader
INFO 2024-03-09 12:53:29,312 views 7272 16824 It's tails!
ERROR 2024-03-09 12:53:29,342 log 7272 16824 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 35, in coin
    return HttpResponse(template.render(side=coin_, context=context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Template.render() got an unexpected keyword argument 'side'
ERROR 2024-03-09 12:53:29,343 basehttp 7272 16824 "GET /task05/coin/ HTTP/1.1" 500 66172
INFO 2024-03-09 12:53:32,061 views 7272 16824 It's heads!
ERROR 2024-03-09 12:53:32,076 log 7272 16824 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 35, in coin
    return HttpResponse(template.render(side=coin_, context=context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Template.render() got an unexpected keyword argument 'side'
ERROR 2024-03-09 12:53:32,077 basehttp 7272 16824 "GET /task05/coin/ HTTP/1.1" 500 66172
INFO 2024-03-09 12:54:01,725 autoreload 7272 18268 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 12:54:02,150 autoreload 6436 15980 Watching for file changes with StatReloader
INFO 2024-03-09 12:54:04,760 views 6436 2588 It's heads!
INFO 2024-03-09 12:54:04,762 basehttp 6436 2588 "GET /task05/coin/ HTTP/1.1" 200 227
INFO 2024-03-09 12:54:09,486 views 6436 2588 It's heads!
INFO 2024-03-09 12:54:09,488 basehttp 6436 2588 "GET /task05/coin/ HTTP/1.1" 200 227
INFO 2024-03-09 12:54:11,054 views 6436 2588 It's heads!
INFO 2024-03-09 12:54:11,056 basehttp 6436 2588 "GET /task05/coin/ HTTP/1.1" 200 227
INFO 2024-03-09 12:54:12,934 views 6436 2588 It's heads!
INFO 2024-03-09 12:54:12,935 basehttp 6436 2588 "GET /task05/coin/ HTTP/1.1" 200 227
INFO 2024-03-09 12:54:14,255 views 6436 2588 It's tails!
INFO 2024-03-09 12:54:14,256 basehttp 6436 2588 "GET /task05/coin/ HTTP/1.1" 200 227
INFO 2024-03-09 12:54:16,141 views 6436 2588 It's tails!
INFO 2024-03-09 12:54:16,142 basehttp 6436 2588 "GET /task05/coin/ HTTP/1.1" 200 227
INFO 2024-03-09 12:54:16,846 views 6436 2588 It's tails!
INFO 2024-03-09 12:54:16,847 basehttp 6436 2588 "GET /task05/coin/ HTTP/1.1" 200 227
INFO 2024-03-09 12:54:17,486 views 6436 2588 It's heads!
INFO 2024-03-09 12:54:17,487 basehttp 6436 2588 "GET /task05/coin/ HTTP/1.1" 200 227
INFO 2024-03-09 12:54:18,126 views 6436 2588 It's heads!
INFO 2024-03-09 12:54:18,127 basehttp 6436 2588 "GET /task05/coin/ HTTP/1.1" 200 227
INFO 2024-03-09 12:59:03,897 autoreload 6436 15980 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 12:59:04,328 autoreload 17156 616 Watching for file changes with StatReloader
INFO 2024-03-09 12:59:51,360 autoreload 17156 616 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 12:59:51,784 autoreload 7524 7936 Watching for file changes with StatReloader
INFO 2024-03-09 13:00:05,645 autoreload 7524 7936 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 13:00:06,071 autoreload 3052 13844 Watching for file changes with StatReloader
INFO 2024-03-09 13:00:10,951 views 3052 15156 tails
INFO 2024-03-09 13:00:10,953 basehttp 3052 15156 "GET /task05/coin/ HTTP/1.1" 200 258
INFO 2024-03-09 13:00:12,068 views 3052 15156 heads
INFO 2024-03-09 13:00:12,069 basehttp 3052 15156 "GET /task05/coin/ HTTP/1.1" 200 300
INFO 2024-03-09 13:00:12,826 views 3052 15156 heads
INFO 2024-03-09 13:00:12,827 basehttp 3052 15156 "GET /task05/coin/ HTTP/1.1" 200 342
INFO 2024-03-09 13:00:13,351 views 3052 15156 tails
INFO 2024-03-09 13:00:13,352 basehttp 3052 15156 "GET /task05/coin/ HTTP/1.1" 200 384
INFO 2024-03-09 13:00:13,867 views 3052 15156 heads
INFO 2024-03-09 13:00:13,869 basehttp 3052 15156 "GET /task05/coin/ HTTP/1.1" 200 426
INFO 2024-03-09 13:00:14,459 views 3052 15156 tails
INFO 2024-03-09 13:00:14,460 basehttp 3052 15156 "GET /task05/coin/ HTTP/1.1" 200 468
INFO 2024-03-09 13:00:14,985 views 3052 15156 heads
INFO 2024-03-09 13:00:14,986 basehttp 3052 15156 "GET /task05/coin/ HTTP/1.1" 200 510
INFO 2024-03-09 13:00:15,401 views 3052 15156 heads
INFO 2024-03-09 13:00:15,402 basehttp 3052 15156 "GET /task05/coin/ HTTP/1.1" 200 552
INFO 2024-03-09 13:00:15,835 views 3052 15156 tails
INFO 2024-03-09 13:00:15,836 basehttp 3052 15156 "GET /task05/coin/ HTTP/1.1" 200 594
INFO 2024-03-09 13:03:26,414 autoreload 3052 13844 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:03:26,855 autoreload 13796 18128 Watching for file changes with StatReloader
INFO 2024-03-09 13:03:29,326 views 13796 6324 heads
INFO 2024-03-09 13:03:29,328 basehttp 13796 6324 "GET /task05/coin/ HTTP/1.1" 200 637
INFO 2024-03-09 13:03:31,235 views 13796 6324 heads
INFO 2024-03-09 13:03:31,236 basehttp 13796 6324 "GET /task05/coin/ HTTP/1.1" 200 637
INFO 2024-03-09 13:03:31,836 views 13796 6324 tails
INFO 2024-03-09 13:03:31,837 basehttp 13796 6324 "GET /task05/coin/ HTTP/1.1" 200 637
INFO 2024-03-09 13:03:32,426 views 13796 6324 heads
INFO 2024-03-09 13:03:32,428 basehttp 13796 6324 "GET /task05/coin/ HTTP/1.1" 200 637
INFO 2024-03-09 13:03:32,943 views 13796 6324 heads
INFO 2024-03-09 13:03:32,944 basehttp 13796 6324 "GET /task05/coin/ HTTP/1.1" 200 637
INFO 2024-03-09 13:05:05,490 views 13796 6324 tails
INFO 2024-03-09 13:05:05,491 basehttp 13796 6324 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:11,233 views 13796 6324 heads
INFO 2024-03-09 13:05:11,238 basehttp 13796 6324 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:12,081 views 13796 6324 tails
INFO 2024-03-09 13:05:12,083 basehttp 13796 6324 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:12,773 views 13796 6324 tails
INFO 2024-03-09 13:05:12,774 basehttp 13796 6324 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:21,364 autoreload 13796 18128 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:05:21,804 autoreload 6840 1688 Watching for file changes with StatReloader
INFO 2024-03-09 13:05:22,915 views 6840 4508 heads
INFO 2024-03-09 13:05:22,916 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:23,106 views 6840 4508 heads
INFO 2024-03-09 13:05:23,107 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:23,715 views 6840 4508 heads
INFO 2024-03-09 13:05:23,716 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:24,249 views 6840 4508 tails
INFO 2024-03-09 13:05:24,254 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:24,739 views 6840 4508 tails
INFO 2024-03-09 13:05:24,740 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:25,214 views 6840 4508 tails
INFO 2024-03-09 13:05:25,215 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:25,664 views 6840 4508 tails
INFO 2024-03-09 13:05:25,665 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:26,006 views 6840 4508 heads
INFO 2024-03-09 13:05:26,008 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:26,348 views 6840 4508 heads
INFO 2024-03-09 13:05:26,349 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:26,723 views 6840 4508 heads
INFO 2024-03-09 13:05:26,725 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:05:27,064 views 6840 4508 tails
INFO 2024-03-09 13:05:27,065 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
ERROR 2024-03-09 13:05:57,646 log 6840 4508 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 27, in coin
    template = loader.get_template("coin.html")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(1)' from 'side.side(1)'
ERROR 2024-03-09 13:05:57,650 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 500 145258
ERROR 2024-03-09 13:06:04,354 log 6840 4508 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 27, in coin
    template = loader.get_template("coin.html")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(0)' from 'side.side(0)'
ERROR 2024-03-09 13:06:04,357 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 500 145258
INFO 2024-03-09 13:06:10,421 views 6840 4508 heads
INFO 2024-03-09 13:06:10,422 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:06:11,896 views 6840 4508 heads
INFO 2024-03-09 13:06:11,897 basehttp 6840 4508 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:07:53,744 autoreload 6840 1688 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:07:54,182 autoreload 18088 7756 Watching for file changes with StatReloader
INFO 2024-03-09 13:07:55,524 views 18088 15812 tails
INFO 2024-03-09 13:07:55,526 basehttp 18088 15812 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:08:07,692 views 18088 15812 tails
INFO 2024-03-09 13:08:07,693 basehttp 18088 15812 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:08:08,325 views 18088 15812 tails
INFO 2024-03-09 13:08:08,326 basehttp 18088 15812 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:10:39,694 views 18088 15812 heads
INFO 2024-03-09 13:10:39,696 basehttp 18088 15812 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:10:41,986 views 18088 15812 tails
INFO 2024-03-09 13:10:41,987 basehttp 18088 15812 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:12:17,739 autoreload 18088 7756 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:12:18,174 autoreload 5852 15848 Watching for file changes with StatReloader
INFO 2024-03-09 13:12:21,566 views 5852 6284 Heads
INFO 2024-03-09 13:12:21,568 basehttp 5852 6284 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:12:22,573 views 5852 6284 Heads
INFO 2024-03-09 13:12:22,575 basehttp 5852 6284 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:12:23,074 views 5852 6284 Heads
INFO 2024-03-09 13:12:23,076 basehttp 5852 6284 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:12:23,532 views 5852 6284 Heads
INFO 2024-03-09 13:12:23,533 basehttp 5852 6284 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:12:23,923 views 5852 6284 Tails
INFO 2024-03-09 13:12:23,925 basehttp 5852 6284 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:12:24,290 views 5852 6284 Tails
INFO 2024-03-09 13:12:24,292 basehttp 5852 6284 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:12:24,758 views 5852 6284 Tails
INFO 2024-03-09 13:12:24,759 basehttp 5852 6284 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:12:25,124 views 5852 6284 Tails
INFO 2024-03-09 13:12:25,125 basehttp 5852 6284 "GET /task05/coin/ HTTP/1.1" 200 1086
INFO 2024-03-09 13:13:22,968 autoreload 5852 15848 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:13:23,395 autoreload 17500 10156 Watching for file changes with StatReloader
INFO 2024-03-09 13:13:55,990 autoreload 17500 10156 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:13:56,424 autoreload 15984 15040 Watching for file changes with StatReloader
INFO 2024-03-09 13:14:16,575 autoreload 15984 15040 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:14:16,993 autoreload 6736 4708 Watching for file changes with StatReloader
INFO 2024-03-09 13:14:18,386 views 6736 1776 Tails
INFO 2024-03-09 13:14:18,388 basehttp 6736 1776 "GET /task05/coin/ HTTP/1.1" 200 926
INFO 2024-03-09 13:14:40,264 autoreload 6736 4708 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:14:40,702 autoreload 15996 18288 Watching for file changes with StatReloader
INFO 2024-03-09 13:14:42,602 views 15996 17672 Tails
INFO 2024-03-09 13:14:42,604 basehttp 15996 17672 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:14:54,769 autoreload 15996 18288 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:14:55,198 autoreload 12368 16680 Watching for file changes with StatReloader
INFO 2024-03-09 13:14:56,652 views 12368 9392 Tails
INFO 2024-03-09 13:14:56,653 basehttp 12368 9392 "GET /task05/coin/ HTTP/1.1" 200 936
INFO 2024-03-09 13:15:26,863 autoreload 12368 16680 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:15:27,313 autoreload 15080 10956 Watching for file changes with StatReloader
INFO 2024-03-09 13:15:30,033 views 15080 8072 Tails
INFO 2024-03-09 13:15:30,035 basehttp 15080 8072 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:15:35,667 views 15080 8072 Heads
INFO 2024-03-09 13:15:35,667 basehttp 15080 8072 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:15:36,468 views 15080 8072 Heads
INFO 2024-03-09 13:15:36,473 basehttp 15080 8072 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:15:37,017 views 15080 8072 Tails
INFO 2024-03-09 13:15:37,018 basehttp 15080 8072 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:15:37,475 views 15080 8072 Heads
INFO 2024-03-09 13:15:37,476 basehttp 15080 8072 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:15:37,941 views 15080 8072 Heads
INFO 2024-03-09 13:15:37,942 basehttp 15080 8072 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:15:38,450 views 15080 8072 Heads
INFO 2024-03-09 13:15:38,451 basehttp 15080 8072 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:15:38,918 views 15080 8072 Tails
INFO 2024-03-09 13:15:38,921 basehttp 15080 8072 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:15:39,367 views 15080 8072 Tails
INFO 2024-03-09 13:15:39,368 basehttp 15080 8072 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:15:39,808 views 15080 8072 Tails
INFO 2024-03-09 13:15:39,809 basehttp 15080 8072 "GET /task05/coin/ HTTP/1.1" 200 946
INFO 2024-03-09 13:15:55,856 autoreload 15080 10956 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:15:56,291 autoreload 17396 16864 Watching for file changes with StatReloader
INFO 2024-03-09 13:15:58,915 views 17396 10992 Heads
INFO 2024-03-09 13:15:58,917 basehttp 17396 10992 "GET /task05/coin/ HTTP/1.1" 200 976
INFO 2024-03-09 13:16:52,793 autoreload 17396 16864 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:16:53,223 autoreload 8356 10124 Watching for file changes with StatReloader
INFO 2024-03-09 13:16:56,821 views 8356 10460 Heads
ERROR 2024-03-09 13:16:56,858 log 8356 10460 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 36, in coin
    return HttpResponse(template.render(context=context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py", line 15, in __str__
    return f"Сторона: {self.side(side)}, время: {self.timestamp.strftime('%d-%h-%Y, %H:%M:%S')}."
                                 ^^^^
NameError: name 'side' is not defined
ERROR 2024-03-09 13:16:56,863 basehttp 8356 10460 "GET /task05/coin/ HTTP/1.1" 500 114358
INFO 2024-03-09 13:17:02,304 autoreload 8356 10124 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:17:02,730 autoreload 13076 11036 Watching for file changes with StatReloader
INFO 2024-03-09 13:17:03,905 views 13076 12728 Heads
ERROR 2024-03-09 13:17:03,941 log 13076 12728 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 36, in coin
    return HttpResponse(template.render(context=context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py", line 15, in __str__
    return f"Сторона: {self.side()}, время: {self.timestamp.strftime('%d-%h-%Y, %H:%M:%S')}."
                       ^^^^^^^^^^^
TypeError: 'str' object is not callable
ERROR 2024-03-09 13:17:03,945 basehttp 13076 12728 "GET /task05/coin/ HTTP/1.1" 500 114388
INFO 2024-03-09 13:17:08,329 autoreload 13076 11036 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:17:08,771 autoreload 11712 8108 Watching for file changes with StatReloader
INFO 2024-03-09 13:17:10,354 views 11712 15340 Heads
ERROR 2024-03-09 13:17:10,389 log 11712 15340 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 36, in coin
    return HttpResponse(template.render(context=context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py", line 15, in __str__
    return f"Сторона: {self.side(0)}, время: {self.timestamp.strftime('%d-%h-%Y, %H:%M:%S')}."
                       ^^^^^^^^^^^^
TypeError: 'str' object is not callable
ERROR 2024-03-09 13:17:10,393 basehttp 11712 15340 "GET /task05/coin/ HTTP/1.1" 500 114392
INFO 2024-03-09 13:17:12,746 views 11712 15340 Heads
ERROR 2024-03-09 13:17:12,766 log 11712 15340 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 36, in coin
    return HttpResponse(template.render(context=context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py", line 15, in __str__
    return f"Сторона: {self.side(0)}, время: {self.timestamp.strftime('%d-%h-%Y, %H:%M:%S')}."
                       ^^^^^^^^^^^^
TypeError: 'str' object is not callable
ERROR 2024-03-09 13:17:12,769 basehttp 11712 15340 "GET /task05/coin/ HTTP/1.1" 500 114392
INFO 2024-03-09 13:17:18,692 autoreload 11712 8108 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-09 13:17:19,121 autoreload 1960 12272 Watching for file changes with StatReloader
INFO 2024-03-09 13:17:20,429 views 1960 9792 Tails
INFO 2024-03-09 13:17:20,431 basehttp 1960 9792 "GET /task05/coin/ HTTP/1.1" 200 976
INFO 2024-03-09 13:17:54,716 autoreload 1960 12272 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 13:17:55,141 autoreload 7584 6664 Watching for file changes with StatReloader
INFO 2024-03-09 13:17:56,270 views 7584 10344 Heads
INFO 2024-03-09 13:17:56,272 basehttp 7584 10344 "GET /task05/coin/ HTTP/1.1" 200 980
INFO 2024-03-09 13:17:56,594 views 7584 10344 Tails
INFO 2024-03-09 13:17:56,596 basehttp 7584 10344 "GET /task05/coin/ HTTP/1.1" 200 984
INFO 2024-03-09 13:17:57,520 views 7584 10344 Tails
INFO 2024-03-09 13:17:57,521 basehttp 7584 10344 "GET /task05/coin/ HTTP/1.1" 200 988
INFO 2024-03-09 13:17:58,177 views 7584 10344 Heads
INFO 2024-03-09 13:17:58,179 basehttp 7584 10344 "GET /task05/coin/ HTTP/1.1" 200 992
INFO 2024-03-09 13:17:58,619 views 7584 10344 Heads
INFO 2024-03-09 13:17:58,620 basehttp 7584 10344 "GET /task05/coin/ HTTP/1.1" 200 996
INFO 2024-03-09 13:17:58,878 views 7584 10344 Tails
INFO 2024-03-09 13:17:58,879 basehttp 7584 10344 "GET /task05/coin/ HTTP/1.1" 200 1000
INFO 2024-03-09 13:17:59,102 views 7584 10344 Heads
INFO 2024-03-09 13:17:59,104 basehttp 7584 10344 "GET /task05/coin/ HTTP/1.1" 200 1004
INFO 2024-03-09 13:17:59,327 views 7584 10344 Tails
INFO 2024-03-09 13:17:59,329 basehttp 7584 10344 "GET /task05/coin/ HTTP/1.1" 200 1008
INFO 2024-03-09 13:17:59,544 views 7584 10344 Heads
INFO 2024-03-09 13:17:59,545 basehttp 7584 10344 "GET /task05/coin/ HTTP/1.1" 200 1012
INFO 2024-03-09 13:24:06,067 autoreload 7584 6664 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 13:24:06,497 autoreload 5148 16984 Watching for file changes with StatReloader
INFO 2024-03-09 13:25:04,872 autoreload 5148 16984 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\urls.py changed, reloading.
INFO 2024-03-09 13:25:05,302 autoreload 8968 12664 Watching for file changes with StatReloader
INFO 2024-03-09 13:25:32,516 autoreload 8968 12664 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 13:25:32,953 autoreload 18128 13860 Watching for file changes with StatReloader
INFO 2024-03-09 13:26:16,407 autoreload 13288 16740 Watching for file changes with StatReloader
INFO 2024-03-09 13:26:20,867 views 13288 17624 Heads
INFO 2024-03-09 13:26:20,869 basehttp 13288 17624 "GET /task05/coin/10 HTTP/1.1" 200 1016
INFO 2024-03-09 13:26:24,575 views 13288 17624 Tails
INFO 2024-03-09 13:26:24,577 basehttp 13288 17624 "GET /task05/coin/20 HTTP/1.1" 200 1780
WARNING 2024-03-09 13:26:28,708 log 13288 17624 Not Found: /task05/coin/
WARNING 2024-03-09 13:26:28,708 basehttp 13288 17624 "GET /task05/coin/ HTTP/1.1" 404 3164
INFO 2024-03-09 13:26:47,063 autoreload 13288 16740 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 13:26:47,505 autoreload 8268 7756 Watching for file changes with StatReloader
WARNING 2024-03-09 13:26:48,593 log 8268 17804 Not Found: /task05/coin/
WARNING 2024-03-09 13:26:48,593 basehttp 8268 17804 "GET /task05/coin/ HTTP/1.1" 404 3164
WARNING 2024-03-09 13:26:50,176 log 8268 17804 Not Found: /task05/coin/
WARNING 2024-03-09 13:26:50,177 basehttp 8268 17804 "GET /task05/coin/ HTTP/1.1" 404 3164
INFO 2024-03-09 13:26:53,617 views 8268 17804 Tails
INFO 2024-03-09 13:26:53,618 basehttp 8268 17804 "GET /task05/coin/1 HTTP/1.1" 200 296
INFO 2024-03-09 13:26:57,734 views 8268 17804 Tails
INFO 2024-03-09 13:26:57,739 basehttp 8268 17804 "GET /task05/coin/0 HTTP/1.1" 200 216
INFO 2024-03-09 13:27:01,380 autoreload 8268 7756 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 13:27:01,812 autoreload 5844 15028 Watching for file changes with StatReloader
WARNING 2024-03-09 13:27:05,824 log 5844 5828 Not Found: /task05/coin/
WARNING 2024-03-09 13:27:05,825 basehttp 5844 5828 "GET /task05/coin/ HTTP/1.1" 404 3164
INFO 2024-03-09 13:27:21,026 autoreload 5844 15028 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 13:27:21,451 autoreload 14992 9392 Watching for file changes with StatReloader
INFO 2024-03-09 13:27:37,363 autoreload 14992 9392 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\urls.py changed, reloading.
INFO 2024-03-09 13:27:37,799 autoreload 15548 14900 Watching for file changes with StatReloader
ERROR 2024-03-09 13:27:38,914 log 15548 8844 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: coin() missing 1 required positional argument: 'amount_of_flips'
ERROR 2024-03-09 13:27:38,915 basehttp 15548 8844 "GET /task05/coin/ HTTP/1.1" 500 61523
INFO 2024-03-09 13:27:49,628 autoreload 15548 14900 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 13:27:50,078 autoreload 15252 2416 Watching for file changes with StatReloader
INFO 2024-03-09 13:27:52,463 views 15252 2176 Tails
INFO 2024-03-09 13:27:52,465 basehttp 15252 2176 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:27:56,231 views 15252 2176 Tails
INFO 2024-03-09 13:27:56,233 basehttp 15252 2176 "GET /task05/coin/50 HTTP/1.1" 200 4076
INFO 2024-03-09 13:27:59,405 views 15252 2176 Tails
INFO 2024-03-09 13:27:59,406 basehttp 15252 2176 "GET /task05/coin/ HTTP/1.1" 200 456
INFO 2024-03-09 13:28:30,039 autoreload 15252 2416 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-09 13:28:30,465 autoreload 13824 10936 Watching for file changes with StatReloader
INFO 2024-03-09 13:33:11,245 autoreload 13824 10936 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\models.py changed, reloading.
INFO 2024-03-09 13:33:11,674 autoreload 18032 17824 Watching for file changes with StatReloader
INFO 2024-03-09 13:54:45,635 autoreload 18076 18244 Watching for file changes with StatReloader
INFO 2024-03-09 13:54:52,632 basehttp 18076 14692 "GET /blog/ HTTP/1.1" 200 13
INFO 2024-03-09 13:55:07,998 autoreload 18076 18244 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\views.py changed, reloading.
INFO 2024-03-09 13:55:08,436 autoreload 15908 9240 Watching for file changes with StatReloader
INFO 2024-03-09 13:55:18,176 autoreload 15908 9240 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\views.py changed, reloading.
INFO 2024-03-09 13:55:18,608 autoreload 15136 6448 Watching for file changes with StatReloader
INFO 2024-03-09 13:55:19,700 basehttp 15136 3004 "GET /blog/ HTTP/1.1" 200 17
INFO 2024-03-09 14:01:10,346 autoreload 15136 6448 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\models.py changed, reloading.
INFO 2024-03-09 14:01:10,777 autoreload 2404 12340 Watching for file changes with StatReloader
INFO 2024-03-09 14:01:38,852 autoreload 2404 12340 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\models.py changed, reloading.
INFO 2024-03-09 14:01:39,264 autoreload 9020 7624 Watching for file changes with StatReloader
INFO 2024-03-09 14:01:55,017 autoreload 9020 7624 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\models.py changed, reloading.
INFO 2024-03-09 14:01:55,436 autoreload 16248 11616 Watching for file changes with StatReloader
INFO 2024-03-09 14:02:25,613 autoreload 16248 11616 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\models.py changed, reloading.
INFO 2024-03-09 14:02:26,038 autoreload 12212 11532 Watching for file changes with StatReloader
INFO 2024-03-09 14:02:59,999 basehttp 12212 1128 "GET /blog/ HTTP/1.1" 200 17
INFO 2024-03-09 14:04:54,852 autoreload 12212 11532 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\models.py changed, reloading.
INFO 2024-03-09 14:04:55,259 autoreload 14528 5920 Watching for file changes with StatReloader
INFO 2024-03-09 14:05:42,002 autoreload 14528 5920 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\models.py changed, reloading.
INFO 2024-03-09 14:05:42,430 autoreload 15204 2764 Watching for file changes with StatReloader
INFO 2024-03-09 14:06:48,083 autoreload 15204 2764 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\models.py changed, reloading.
INFO 2024-03-09 14:06:48,532 autoreload 9948 8836 Watching for file changes with StatReloader
INFO 2024-03-09 14:06:57,225 autoreload 9948 8836 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\models.py changed, reloading.
INFO 2024-03-09 14:06:57,663 autoreload 15604 10544 Watching for file changes with StatReloader
INFO 2024-03-09 14:09:29,329 autoreload 15604 10544 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\models.py changed, reloading.
INFO 2024-03-09 14:09:29,766 autoreload 16124 12372 Watching for file changes with StatReloader
INFO 2024-03-09 14:10:04,657 autoreload 1316 3064 Watching for file changes with StatReloader
INFO 2024-03-09 14:29:22,429 autoreload 536 15052 Watching for file changes with StatReloader
INFO 2024-03-09 14:31:35,038 autoreload 11400 16468 Watching for file changes with StatReloader
INFO 2024-03-09 14:35:13,735 autoreload 11032 10584 Watching for file changes with StatReloader
INFO 2024-03-12 12:38:41,754 autoreload 13340 16036 Watching for file changes with StatReloader
ERROR 2024-03-12 12:38:54,106 log 13340 5244 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py", line 11, in index
    template = loader.get_template("index.html")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2024-03-12 12:38:54,108 basehttp 13340 5244 "GET / HTTP/1.1" 500 72387
WARNING 2024-03-12 12:38:54,197 log 13340 5244 Not Found: /favicon.ico
WARNING 2024-03-12 12:38:54,197 basehttp 13340 5244 "GET /favicon.ico HTTP/1.1" 404 2756
INFO 2024-03-12 12:39:32,236 autoreload 13340 16036 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-12 12:39:32,675 autoreload 21116 10164 Watching for file changes with StatReloader
INFO 2024-03-12 12:39:34,586 views 21116 12116 Index page accessed
INFO 2024-03-12 12:39:34,589 basehttp 21116 12116 "GET / HTTP/1.1" 200 397
ERROR 2024-03-12 12:39:36,733 log 21116 12116 Internal Server Error: /shop/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\shop\views.py", line 9, in index
    template = loader.get_template("index.html")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2024-03-12 12:39:36,734 basehttp 21116 12116 "GET /shop/ HTTP/1.1" 500 72053
INFO 2024-03-12 12:40:09,807 autoreload 21116 10164 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\lessons\urls.py changed, reloading.
INFO 2024-03-12 12:40:10,240 autoreload 9008 13148 Watching for file changes with StatReloader
WARNING 2024-03-12 12:40:11,326 log 9008 16652 Not Found: /shop/
WARNING 2024-03-12 12:40:11,326 basehttp 9008 16652 "GET /shop/ HTTP/1.1" 404 2633
INFO 2024-03-12 12:40:11,843 views 9008 16652 Index page accessed
INFO 2024-03-12 12:40:11,846 basehttp 9008 16652 "GET / HTTP/1.1" 200 397
INFO 2024-03-12 12:40:12,866 basehttp 9008 16652 "GET /blog/ HTTP/1.1" 200 17
WARNING 2024-03-12 12:40:16,190 log 9008 16652 Not Found: /about//
WARNING 2024-03-12 12:40:16,190 basehttp 9008 16652 "GET /about// HTTP/1.1" 404 2639
WARNING 2024-03-12 12:40:55,888 log 9008 16652 Not Found: /about//
WARNING 2024-03-12 12:40:55,889 basehttp 9008 16652 "GET /about// HTTP/1.1" 404 2639
INFO 2024-03-12 12:40:57,069 views 9008 16652 Index page accessed
ERROR 2024-03-12 12:40:57,108 log 9008 16652 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py", line 13, in index
    return HttpResponse(template.render())
                        ^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'myapp/index' not found. 'myapp/index' is not a valid view function or pattern name.
ERROR 2024-03-12 12:40:57,112 basehttp 9008 16652 "GET / HTTP/1.1" 500 131553
INFO 2024-03-12 12:42:21,657 autoreload 9008 13148 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\views.py changed, reloading.
INFO 2024-03-12 12:42:22,094 autoreload 18356 19484 Watching for file changes with StatReloader
INFO 2024-03-12 12:42:27,170 views 18356 16040 Index page accessed
INFO 2024-03-12 12:42:27,173 basehttp 18356 16040 "GET / HTTP/1.1" 200 397
INFO 2024-03-12 12:42:28,581 basehttp 18356 16040 "GET /blog/ HTTP/1.1" 200 17
INFO 2024-03-12 12:42:32,629 basehttp 18356 16040 "GET /blog/ HTTP/1.1" 200 17
INFO 2024-03-12 12:42:33,741 views 18356 16040 Index page accessed
INFO 2024-03-12 12:42:33,742 basehttp 18356 16040 "GET / HTTP/1.1" 200 397
INFO 2024-03-12 12:42:34,787 basehttp 18356 16040 "GET /blog/ HTTP/1.1" 200 17
INFO 2024-03-12 12:42:51,780 autoreload 18356 19484 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\blog\urls.py changed, reloading.
INFO 2024-03-12 12:42:52,232 autoreload 1864 12608 Watching for file changes with StatReloader
INFO 2024-03-12 12:42:55,313 views 1864 11128 Index page accessed
INFO 2024-03-12 12:42:55,316 basehttp 1864 11128 "GET / HTTP/1.1" 200 399
INFO 2024-03-12 12:43:13,574 autoreload 1864 12608 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\urls.py changed, reloading.
INFO 2024-03-12 12:43:14,011 autoreload 3996 22752 Watching for file changes with StatReloader
INFO 2024-03-12 12:43:20,649 autoreload 3996 22752 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 12:43:21,084 autoreload 13456 22392 Watching for file changes with StatReloader
INFO 2024-03-12 12:43:29,744 autoreload 13456 22392 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\urls.py changed, reloading.
INFO 2024-03-12 12:43:30,174 autoreload 16244 20312 Watching for file changes with StatReloader
INFO 2024-03-12 12:43:31,327 views 16244 5348 Index page accessed
INFO 2024-03-12 12:43:31,330 basehttp 16244 5348 "GET / HTTP/1.1" 200 392
INFO 2024-03-12 12:44:33,817 autoreload 16244 20312 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\lessons\urls.py changed, reloading.
INFO 2024-03-12 12:44:34,309 autoreload 7132 6152 Watching for file changes with StatReloader
INFO 2024-03-12 12:44:39,514 views 7132 13024 Index page accessed
INFO 2024-03-12 12:44:39,516 basehttp 7132 13024 "GET / HTTP/1.1" 200 392
INFO 2024-03-12 12:44:59,828 autoreload 7132 6152 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\urls.py changed, reloading.
INFO 2024-03-12 12:45:00,265 autoreload 18132 11280 Watching for file changes with StatReloader
INFO 2024-03-12 12:45:01,274 views 18132 21936 Index page accessed
INFO 2024-03-12 12:45:01,276 basehttp 18132 21936 "GET / HTTP/1.1" 200 391
WARNING 2024-03-12 12:45:03,683 log 18132 21936 Not Found: /about/
WARNING 2024-03-12 12:45:03,683 basehttp 18132 21936 "GET /about/ HTTP/1.1" 404 2740
INFO 2024-03-12 12:45:37,007 autoreload 18132 11280 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\urls.py changed, reloading.
INFO 2024-03-12 12:45:37,475 autoreload 18200 21172 Watching for file changes with StatReloader
INFO 2024-03-12 12:45:41,106 views 18200 14144 About page accessed
INFO 2024-03-12 12:45:41,109 basehttp 18200 14144 "GET /about/ HTTP/1.1" 200 445
INFO 2024-03-12 12:45:57,794 autoreload 18200 21172 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\urls.py changed, reloading.
INFO 2024-03-12 12:45:58,239 autoreload 17636 17888 Watching for file changes with StatReloader
WARNING 2024-03-12 12:46:33,983 log 17636 8012 Not Found: /about/
WARNING 2024-03-12 12:46:33,984 basehttp 17636 8012 "GET /about/ HTTP/1.1" 404 2740
INFO 2024-03-12 12:46:43,975 views 17636 8012 About page accessed
INFO 2024-03-12 12:46:43,978 basehttp 17636 8012 "GET /about HTTP/1.1" 200 444
WARNING 2024-03-12 12:46:46,860 log 17636 8012 Not Found: /about/
WARNING 2024-03-12 12:46:46,861 basehttp 17636 8012 "GET /about/ HTTP/1.1" 404 2740
INFO 2024-03-12 12:50:46,237 autoreload 17636 17888 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\urls.py changed, reloading.
INFO 2024-03-12 12:50:46,690 autoreload 20544 8228 Watching for file changes with StatReloader
INFO 2024-03-12 12:52:01,129 views 20544 18868 About page accessed
INFO 2024-03-12 12:52:01,130 basehttp 20544 18868 "GET /about/ HTTP/1.1" 200 276
INFO 2024-03-12 12:52:15,428 views 20544 18868 About page accessed
INFO 2024-03-12 12:52:15,431 basehttp 20544 18868 "GET /about/ HTTP/1.1" 200 446
WARNING 2024-03-12 12:52:17,645 log 20544 18868 Not Found: /about//
WARNING 2024-03-12 12:52:17,645 basehttp 20544 18868 "GET /about// HTTP/1.1" 404 2744
WARNING 2024-03-12 12:52:42,038 log 20544 18868 Not Found: /about//
WARNING 2024-03-12 12:52:42,039 basehttp 20544 18868 "GET /about// HTTP/1.1" 404 2744
INFO 2024-03-12 12:52:43,221 views 20544 18868 About page accessed
INFO 2024-03-12 12:52:43,222 basehttp 20544 18868 "GET /about/ HTTP/1.1" 200 640
INFO 2024-03-12 12:52:44,730 views 20544 18868 About page accessed
INFO 2024-03-12 12:52:44,731 basehttp 20544 18868 "GET /about/ HTTP/1.1" 200 640
INFO 2024-03-12 12:52:46,163 views 20544 18868 Index page accessed
INFO 2024-03-12 12:52:46,164 basehttp 20544 18868 "GET / HTTP/1.1" 200 588
INFO 2024-03-12 12:52:47,199 views 20544 18868 Index page accessed
INFO 2024-03-12 12:52:47,199 basehttp 20544 18868 "GET / HTTP/1.1" 200 588
INFO 2024-03-12 12:52:48,533 views 20544 18868 About page accessed
INFO 2024-03-12 12:52:48,534 basehttp 20544 18868 "GET /about/ HTTP/1.1" 200 640
INFO 2024-03-12 12:54:58,076 autoreload 20544 8228 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-12 12:54:58,533 autoreload 20236 17672 Watching for file changes with StatReloader
INFO 2024-03-12 12:55:00,368 views 20236 1932 About page accessed
ERROR 2024-03-12 12:55:00,396 log 20236 1932 Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'SafeString' object has no attribute 'get'
ERROR 2024-03-12 12:55:00,397 basehttp 20236 1932 "GET /about/ HTTP/1.1" 500 66693
INFO 2024-03-12 12:55:17,823 autoreload 20236 17672 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-12 12:55:18,263 autoreload 14368 628 Watching for file changes with StatReloader
INFO 2024-03-12 13:06:33,501 autoreload 14368 628 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-12 13:06:33,961 autoreload 13644 19248 Watching for file changes with StatReloader
INFO 2024-03-12 13:06:36,327 views 13644 14492 About page accessed
INFO 2024-03-12 13:06:36,329 basehttp 13644 14492 "GET /about/ HTTP/1.1" 200 443
INFO 2024-03-12 13:06:37,771 views 13644 14492 Index page accessed
ERROR 2024-03-12 13:06:37,807 log 13644 14492 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py", line 13, in index
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 17, in get_template
    for origin in self.get_template_sources(template_name):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 70, in get_template_sources
    yield from loader.get_template_sources(template_name)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\filesystem.py", line 35, in get_template_sources
    name = safe_join(template_dir, template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
                         ^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 147, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'Template'
ERROR 2024-03-12 13:06:37,811 basehttp 13644 14492 "GET / HTTP/1.1" 500 121828
INFO 2024-03-12 13:07:12,144 autoreload 13644 19248 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-12 13:07:12,583 autoreload 8416 15044 Watching for file changes with StatReloader
INFO 2024-03-12 13:07:13,611 views 8416 14212 Index page accessed
INFO 2024-03-12 13:07:13,619 basehttp 8416 14212 "GET / HTTP/1.1" 200 389
INFO 2024-03-12 13:07:16,763 views 8416 14212 Index page accessed
INFO 2024-03-12 13:07:16,764 basehttp 8416 14212 "GET / HTTP/1.1" 200 389
INFO 2024-03-12 13:07:48,248 autoreload 8416 15044 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py changed, reloading.
INFO 2024-03-12 13:07:48,689 autoreload 15188 15948 Watching for file changes with StatReloader
INFO 2024-03-12 13:07:50,240 views 15188 13276 About page accessed
INFO 2024-03-12 13:07:50,245 basehttp 15188 13276 "GET /about/ HTTP/1.1" 200 443
INFO 2024-03-12 13:07:51,710 views 15188 13276 Index page accessed
INFO 2024-03-12 13:07:51,711 basehttp 15188 13276 "GET / HTTP/1.1" 200 389
INFO 2024-03-12 13:07:52,687 views 15188 13276 About page accessed
INFO 2024-03-12 13:07:52,688 basehttp 15188 13276 "GET /about/ HTTP/1.1" 200 443
INFO 2024-03-12 13:10:42,603 views 15188 13276 Index page accessed
INFO 2024-03-12 13:10:42,604 basehttp 15188 13276 "GET / HTTP/1.1" 200 231
INFO 2024-03-12 13:11:08,499 views 15188 13276 Index page accessed
INFO 2024-03-12 13:11:08,501 basehttp 15188 13276 "GET / HTTP/1.1" 200 231
INFO 2024-03-12 13:11:10,032 views 15188 13276 Index page accessed
INFO 2024-03-12 13:11:10,033 basehttp 15188 13276 "GET / HTTP/1.1" 200 231
INFO 2024-03-12 13:11:43,332 views 15188 13276 Index page accessed
INFO 2024-03-12 13:11:43,334 basehttp 15188 13276 "GET / HTTP/1.1" 200 231
INFO 2024-03-12 13:12:02,474 views 15188 13276 Index page accessed
INFO 2024-03-12 13:12:02,476 basehttp 15188 13276 "GET / HTTP/1.1" 200 231
INFO 2024-03-12 13:12:56,370 views 15188 13276 Index page accessed
INFO 2024-03-12 13:12:56,371 basehttp 15188 13276 "GET / HTTP/1.1" 200 231
INFO 2024-03-12 13:13:41,299 views 15188 13276 Index page accessed
INFO 2024-03-12 13:13:41,300 basehttp 15188 13276 "GET / HTTP/1.1" 200 231
INFO 2024-03-12 13:14:02,851 views 15188 13276 Index page accessed
INFO 2024-03-12 13:14:02,853 basehttp 15188 13276 "GET / HTTP/1.1" 200 231
INFO 2024-03-12 13:17:06,210 views 15188 13276 Index page accessed
INFO 2024-03-12 13:17:06,211 basehttp 15188 13276 "GET / HTTP/1.1" 200 231
INFO 2024-03-12 13:17:19,699 views 15188 13276 Index page accessed
INFO 2024-03-12 13:17:19,701 basehttp 15188 13276 "GET / HTTP/1.1" 200 240
INFO 2024-03-12 13:17:55,827 views 15188 13276 Index page accessed
INFO 2024-03-12 13:17:55,828 basehttp 15188 13276 "GET / HTTP/1.1" 200 240
INFO 2024-03-12 13:18:06,098 views 15188 13276 Index page accessed
INFO 2024-03-12 13:18:06,099 basehttp 15188 13276 "GET / HTTP/1.1" 200 240
INFO 2024-03-12 13:18:22,188 views 15188 13276 Index page accessed
INFO 2024-03-12 13:18:22,189 basehttp 15188 13276 "GET / HTTP/1.1" 200 240
INFO 2024-03-12 13:18:32,403 views 15188 13276 Index page accessed
ERROR 2024-03-12 13:18:32,436 log 15188 13276 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py", line 13, in index
    return render(request, template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 297, in do_extends
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'extends' cannot appear more than once in the same template
ERROR 2024-03-12 13:18:32,441 basehttp 15188 13276 "GET / HTTP/1.1" 500 132169
INFO 2024-03-12 13:18:56,643 views 15188 13276 Index page accessed
INFO 2024-03-12 13:18:56,645 basehttp 15188 13276 "GET / HTTP/1.1" 200 395
INFO 2024-03-12 13:19:22,212 views 15188 13276 Index page accessed
ERROR 2024-03-12 13:19:22,234 log 15188 13276 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: menu.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py", line 13, in index
    return render(request, template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: menu.html
ERROR 2024-03-12 13:19:22,238 basehttp 15188 13276 "GET / HTTP/1.1" 500 131867
INFO 2024-03-12 13:19:31,924 views 15188 13276 Index page accessed
ERROR 2024-03-12 13:19:31,946 log 15188 13276 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: menu.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\myapp\views.py", line 13, in index
    return render(request, template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: menu.html
ERROR 2024-03-12 13:19:31,949 basehttp 15188 13276 "GET / HTTP/1.1" 500 131867
INFO 2024-03-12 13:19:45,899 views 15188 13276 Index page accessed
INFO 2024-03-12 13:19:45,901 basehttp 15188 13276 "GET / HTTP/1.1" 200 395
INFO 2024-03-12 13:19:50,233 views 15188 13276 Index page accessed
INFO 2024-03-12 13:19:50,233 basehttp 15188 13276 "GET / HTTP/1.1" 200 395
INFO 2024-03-12 13:19:51,265 views 15188 13276 About page accessed
INFO 2024-03-12 13:19:51,266 basehttp 15188 13276 "GET /about/ HTTP/1.1" 200 449
INFO 2024-03-12 13:20:07,677 views 15188 13276 About page accessed
INFO 2024-03-12 13:20:07,679 basehttp 15188 13276 "GET /about/ HTTP/1.1" 200 449
INFO 2024-03-12 13:20:10,980 views 15188 13276 About page accessed
INFO 2024-03-12 13:20:10,982 basehttp 15188 13276 "GET /about/ HTTP/1.1" 200 449
INFO 2024-03-12 13:20:13,314 views 15188 13276 Index page accessed
INFO 2024-03-12 13:20:13,315 basehttp 15188 13276 "GET / HTTP/1.1" 200 395
INFO 2024-03-12 13:20:14,171 views 15188 13276 Index page accessed
INFO 2024-03-12 13:20:14,172 basehttp 15188 13276 "GET / HTTP/1.1" 200 395
INFO 2024-03-12 13:20:14,735 views 15188 13276 About page accessed
INFO 2024-03-12 13:20:14,735 basehttp 15188 13276 "GET /about/ HTTP/1.1" 200 449
INFO 2024-03-12 13:21:15,899 autoreload 15188 15948 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\lessons\urls.py changed, reloading.
INFO 2024-03-12 13:21:16,297 autoreload 18164 17636 Watching for file changes with StatReloader
INFO 2024-03-12 13:24:09,831 autoreload 11624 7156 Watching for file changes with StatReloader
INFO 2024-03-12 13:24:15,057 views 11624 20092 Index page accessed
INFO 2024-03-12 13:24:15,058 basehttp 11624 20092 "GET /task05/ HTTP/1.1" 200 9
INFO 2024-03-12 13:32:55,563 autoreload 11624 7156 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 13:32:56,008 autoreload 5572 11392 Watching for file changes with StatReloader
INFO 2024-03-12 13:33:06,810 autoreload 5572 11392 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 13:33:07,259 autoreload 13792 9972 Watching for file changes with StatReloader
INFO 2024-03-12 13:33:46,027 autoreload 13792 9972 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 13:33:46,480 autoreload 7052 20952 Watching for file changes with StatReloader
INFO 2024-03-12 13:33:52,263 views 7052 18576 Index page accessed
INFO 2024-03-12 13:33:52,264 basehttp 7052 18576 "GET /task05/ HTTP/1.1" 200 9
INFO 2024-03-12 13:33:56,806 views 7052 18576 Tails
ERROR 2024-03-12 13:33:56,843 log 7052 18576 Internal Server Error: /task05/coin/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: menu.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 32, in coin
    return render(request, template_name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: menu.html
ERROR 2024-03-12 13:33:56,846 basehttp 7052 18576 "GET /task05/coin/ HTTP/1.1" 500 133358
INFO 2024-03-12 13:34:16,656 views 7052 18576 Tails
INFO 2024-03-12 13:34:16,659 basehttp 7052 18576 "GET /task05/coin/ HTTP/1.1" 200 386
INFO 2024-03-12 13:35:33,140 autoreload 7052 20952 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 13:35:33,582 autoreload 14876 12588 Watching for file changes with StatReloader
INFO 2024-03-12 13:35:51,219 views 14876 15272 Heads
INFO 2024-03-12 13:35:51,225 basehttp 14876 15272 "GET /task05/coin/ HTTP/1.1" 200 386
INFO 2024-03-12 13:36:11,060 views 14876 15272 Heads
INFO 2024-03-12 13:36:11,062 basehttp 14876 15272 "GET /task05/coin/ HTTP/1.1" 200 427
INFO 2024-03-12 13:37:08,609 autoreload 14876 12588 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 13:37:09,050 autoreload 21272 3884 Watching for file changes with StatReloader
INFO 2024-03-12 13:37:16,809 views 21272 12968 Dice was tossed and gave number 3
INFO 2024-03-12 13:37:16,818 basehttp 21272 12968 "GET /task05/dice/ HTTP/1.1" 200 419
INFO 2024-03-12 13:37:20,136 views 21272 12968 Dice was tossed and gave number 4
INFO 2024-03-12 13:37:20,137 basehttp 21272 12968 "GET /task05/dice/ HTTP/1.1" 200 419
INFO 2024-03-12 13:37:20,680 views 21272 12968 Dice was tossed and gave number 5
INFO 2024-03-12 13:37:20,680 basehttp 21272 12968 "GET /task05/dice/ HTTP/1.1" 200 419
INFO 2024-03-12 13:37:21,080 views 21272 12968 Dice was tossed and gave number 1
INFO 2024-03-12 13:37:21,081 basehttp 21272 12968 "GET /task05/dice/ HTTP/1.1" 200 419
INFO 2024-03-12 13:37:21,435 views 21272 12968 Dice was tossed and gave number 6
INFO 2024-03-12 13:37:21,435 basehttp 21272 12968 "GET /task05/dice/ HTTP/1.1" 200 419
INFO 2024-03-12 13:37:21,747 views 21272 12968 Dice was tossed and gave number 6
INFO 2024-03-12 13:37:21,748 basehttp 21272 12968 "GET /task05/dice/ HTTP/1.1" 200 419
INFO 2024-03-12 13:37:22,020 views 21272 12968 Dice was tossed and gave number 5
INFO 2024-03-12 13:37:22,021 basehttp 21272 12968 "GET /task05/dice/ HTTP/1.1" 200 419
INFO 2024-03-12 13:37:22,260 views 21272 12968 Dice was tossed and gave number 6
INFO 2024-03-12 13:37:22,261 basehttp 21272 12968 "GET /task05/dice/ HTTP/1.1" 200 419
INFO 2024-03-12 13:37:56,356 autoreload 21272 3884 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 13:37:56,807 autoreload 11484 7088 Watching for file changes with StatReloader
INFO 2024-03-12 13:38:06,547 autoreload 11484 7088 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 13:38:06,997 autoreload 20184 14312 Watching for file changes with StatReloader
INFO 2024-03-12 13:38:14,554 views 20184 15016 The random number from 0 to 100 is 84
INFO 2024-03-12 13:38:14,562 basehttp 20184 15016 "GET /task05/random/ HTTP/1.1" 200 460
INFO 2024-03-12 13:38:17,122 views 20184 15016 The random number from 0 to 100 is 66
INFO 2024-03-12 13:38:17,123 basehttp 20184 15016 "GET /task05/random/ HTTP/1.1" 200 460
INFO 2024-03-12 13:38:17,633 views 20184 15016 The random number from 0 to 100 is 25
INFO 2024-03-12 13:38:17,634 basehttp 20184 15016 "GET /task05/random/ HTTP/1.1" 200 460
INFO 2024-03-12 13:38:18,017 views 20184 15016 The random number from 0 to 100 is 44
INFO 2024-03-12 13:38:18,017 basehttp 20184 15016 "GET /task05/random/ HTTP/1.1" 200 460
INFO 2024-03-12 13:39:51,586 views 20184 15016 The random number from 0 to 100 is 54
ERROR 2024-03-12 13:39:51,627 log 20184 15016 Internal Server Error: /task05/random/
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py", line 57, in random_num
    return render(request, template_name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'random_num' not found. 'random_num' is not a valid view function or pattern name.
ERROR 2024-03-12 13:39:51,633 basehttp 20184 15016 "GET /task05/random/ HTTP/1.1" 500 183613
INFO 2024-03-12 13:40:19,627 views 20184 15016 The random number from 0 to 100 is 46
INFO 2024-03-12 13:40:19,629 basehttp 20184 15016 "GET /task05/random/ HTTP/1.1" 200 621
INFO 2024-03-12 13:40:21,667 views 20184 15016 Tails
INFO 2024-03-12 13:40:21,668 basehttp 20184 15016 "GET /task05/coin/ HTTP/1.1" 200 588
INFO 2024-03-12 13:40:24,028 views 20184 15016 Dice was tossed and gave number 3
INFO 2024-03-12 13:40:24,029 basehttp 20184 15016 "GET /task05/dice/ HTTP/1.1" 200 580
INFO 2024-03-12 13:40:25,722 views 20184 15016 The random number from 0 to 100 is 15
INFO 2024-03-12 13:40:25,723 basehttp 20184 15016 "GET /task05/random/ HTTP/1.1" 200 621
INFO 2024-03-12 13:40:28,628 views 20184 15016 The random number from 0 to 100 is 26
INFO 2024-03-12 13:40:28,629 basehttp 20184 15016 "GET /task05/random/ HTTP/1.1" 200 621
INFO 2024-03-12 13:42:58,466 autoreload 20184 14312 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 13:42:58,902 autoreload 18184 19660 Watching for file changes with StatReloader
INFO 2024-03-12 13:43:12,804 autoreload 18184 19660 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 13:43:13,241 autoreload 19824 18792 Watching for file changes with StatReloader
INFO 2024-03-12 13:43:14,225 views 19824 9236 The random number from 0 to 100 is 48
INFO 2024-03-12 13:43:14,234 basehttp 19824 9236 "GET /task05/random/ HTTP/1.1" 200 626
INFO 2024-03-12 13:43:15,619 views 19824 9236 Tails
INFO 2024-03-12 13:43:15,621 basehttp 19824 9236 "GET /task05/coin/ HTTP/1.1" 200 871
INFO 2024-03-12 13:43:17,187 views 19824 9236 Dice was tossed and gave number 6
INFO 2024-03-12 13:43:17,188 basehttp 19824 9236 "GET /task05/dice/ HTTP/1.1" 200 585
INFO 2024-03-12 13:43:18,463 views 19824 9236 The random number from 0 to 100 is 98
INFO 2024-03-12 13:43:18,464 basehttp 19824 9236 "GET /task05/random/ HTTP/1.1" 200 626
INFO 2024-03-12 13:43:19,346 views 19824 9236 Tails
INFO 2024-03-12 13:43:19,348 basehttp 19824 9236 "GET /task05/coin/ HTTP/1.1" 200 871
INFO 2024-03-12 13:43:23,294 views 19824 9236 Tails
INFO 2024-03-12 13:43:23,295 basehttp 19824 9236 "GET /task05/coin/ HTTP/1.1" 200 871
INFO 2024-03-12 13:43:24,129 views 19824 9236 Heads
INFO 2024-03-12 13:43:24,135 basehttp 19824 9236 "GET /task05/coin/ HTTP/1.1" 200 871
INFO 2024-03-12 13:43:24,902 views 19824 9236 Heads
INFO 2024-03-12 13:43:24,903 basehttp 19824 9236 "GET /task05/coin/ HTTP/1.1" 200 871
INFO 2024-03-12 13:43:25,503 views 19824 9236 Heads
INFO 2024-03-12 13:43:25,504 basehttp 19824 9236 "GET /task05/coin/ HTTP/1.1" 200 871
INFO 2024-03-12 13:43:26,094 views 19824 9236 Heads
INFO 2024-03-12 13:43:26,095 basehttp 19824 9236 "GET /task05/coin/ HTTP/1.1" 200 871
INFO 2024-03-12 13:50:48,282 autoreload 19824 18792 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-12 13:50:48,692 autoreload 5212 8228 Watching for file changes with StatReloader
INFO 2024-03-12 13:51:40,453 autoreload 5212 8228 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-12 13:51:40,892 autoreload 18504 8728 Watching for file changes with StatReloader
INFO 2024-03-12 13:51:51,669 autoreload 18504 8728 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-12 13:51:52,107 autoreload 22384 9156 Watching for file changes with StatReloader
INFO 2024-03-12 13:53:45,670 autoreload 22384 9156 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 13:53:46,128 autoreload 22084 16552 Watching for file changes with StatReloader
INFO 2024-03-12 13:56:09,195 autoreload 13848 5460 Watching for file changes with StatReloader
INFO 2024-03-12 13:56:10,599 views 13848 20696 Heads
INFO 2024-03-12 13:56:10,607 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 893
INFO 2024-03-12 13:56:12,107 views 13848 20696 Tails
INFO 2024-03-12 13:56:12,109 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 893
INFO 2024-03-12 13:56:12,765 views 13848 20696 Heads
INFO 2024-03-12 13:56:12,767 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 893
INFO 2024-03-12 13:56:13,332 views 13848 20696 Tails
INFO 2024-03-12 13:56:13,333 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 893
INFO 2024-03-12 13:56:18,075 views 13848 20696 Tails
INFO 2024-03-12 13:56:18,082 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 893
INFO 2024-03-12 13:56:18,800 views 13848 20696 Heads
INFO 2024-03-12 13:56:18,806 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 893
INFO 2024-03-12 13:56:19,365 views 13848 20696 Heads
INFO 2024-03-12 13:56:19,367 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 893
INFO 2024-03-12 13:56:38,464 views 13848 20696 Heads
INFO 2024-03-12 13:56:38,467 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 885
INFO 2024-03-12 13:56:40,939 views 13848 20696 Heads
INFO 2024-03-12 13:56:40,940 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 885
INFO 2024-03-12 13:56:41,692 views 13848 20696 Tails
INFO 2024-03-12 13:56:41,695 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 885
INFO 2024-03-12 13:56:42,273 views 13848 20696 Heads
INFO 2024-03-12 13:56:42,275 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 885
INFO 2024-03-12 13:56:42,772 views 13848 20696 Tails
INFO 2024-03-12 13:56:42,774 basehttp 13848 20696 "GET /task05/coin/ HTTP/1.1" 200 885
INFO 2024-03-12 13:56:46,282 views 13848 20696 Dice was tossed and gave number 5
INFO 2024-03-12 13:56:46,290 basehttp 13848 20696 "GET /task05/dice/ HTTP/1.1" 200 592
INFO 2024-03-12 13:56:47,614 views 13848 20696 Dice was tossed and gave number 6
INFO 2024-03-12 13:56:47,615 basehttp 13848 20696 "GET /task05/dice/ HTTP/1.1" 200 592
INFO 2024-03-12 13:57:37,754 views 13848 20696 Dice was tossed and gave number 2
INFO 2024-03-12 13:57:37,755 basehttp 13848 20696 "GET /task05/dice/ HTTP/1.1" 200 592
INFO 2024-03-12 13:58:31,243 autoreload 13848 5460 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-12 13:58:31,690 autoreload 21248 7100 Watching for file changes with StatReloader
INFO 2024-03-12 13:58:34,110 views 21248 17012 Dice was tossed and gave number 1
INFO 2024-03-12 13:58:34,119 basehttp 21248 17012 "GET /task05/dice/ HTTP/1.1" 200 592
INFO 2024-03-12 13:59:16,842 views 21248 17012 Tails
INFO 2024-03-12 13:59:16,845 basehttp 21248 17012 "GET /task05/coin/ HTTP/1.1" 200 863
INFO 2024-03-12 13:59:18,467 views 21248 17012 Dice was tossed and gave number 6
INFO 2024-03-12 13:59:18,468 basehttp 21248 17012 "GET /task05/dice/ HTTP/1.1" 200 843
INFO 2024-03-12 13:59:21,209 views 21248 17012 Dice was tossed and gave number 4
INFO 2024-03-12 13:59:21,210 basehttp 21248 17012 "GET /task05/dice/ HTTP/1.1" 200 843
INFO 2024-03-12 14:00:47,167 autoreload 21248 7100 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\models.py changed, reloading.
INFO 2024-03-12 14:00:47,604 autoreload 22696 12580 Watching for file changes with StatReloader
INFO 2024-03-12 14:01:10,824 autoreload 22696 12580 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 14:01:11,257 autoreload 1236 13900 Watching for file changes with StatReloader
INFO 2024-03-12 14:01:22,055 autoreload 1236 13900 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 14:01:22,495 autoreload 4564 10472 Watching for file changes with StatReloader
INFO 2024-03-12 14:01:33,276 autoreload 4564 10472 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\views.py changed, reloading.
INFO 2024-03-12 14:02:16,910 autoreload 15112 21424 Watching for file changes with StatReloader
INFO 2024-03-12 14:02:18,201 views 15112 19244 Dice was tossed and gave number 4
INFO 2024-03-12 14:02:18,212 basehttp 15112 19244 "GET /task05/dice/ HTTP/1.1" 200 843
INFO 2024-03-12 14:02:19,918 views 15112 19244 The random number from 0 to 100 is 53
INFO 2024-03-12 14:02:19,920 basehttp 15112 19244 "GET /task05/random/ HTTP/1.1" 200 717
INFO 2024-03-12 14:02:21,761 views 15112 19244 The random number from 0 to 100 is 52
INFO 2024-03-12 14:02:21,767 basehttp 15112 19244 "GET /task05/random/ HTTP/1.1" 200 802
INFO 2024-03-12 14:02:22,453 views 15112 19244 The random number from 0 to 100 is 79
INFO 2024-03-12 14:02:22,454 basehttp 15112 19244 "GET /task05/random/ HTTP/1.1" 200 887
INFO 2024-03-12 14:02:23,477 views 15112 19244 The random number from 0 to 100 is 97
INFO 2024-03-12 14:02:23,478 basehttp 15112 19244 "GET /task05/random/ HTTP/1.1" 200 887
INFO 2024-03-12 14:03:45,698 autoreload 15112 21424 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\urls.py changed, reloading.
INFO 2024-03-12 14:03:46,141 autoreload 10884 13692 Watching for file changes with StatReloader
INFO 2024-03-12 14:03:51,509 autoreload 10884 13692 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\urls.py changed, reloading.
INFO 2024-03-12 14:03:51,948 autoreload 14544 12496 Watching for file changes with StatReloader
INFO 2024-03-12 14:03:57,367 views 14544 11336 The random number from 0 to 100 is 81
INFO 2024-03-12 14:03:57,377 basehttp 14544 11336 "GET /task05/random/ HTTP/1.1" 200 908
WARNING 2024-03-12 14:03:59,956 log 14544 11336 Not Found: /task05/random/10
WARNING 2024-03-12 14:03:59,957 basehttp 14544 11336 "GET /task05/random/10 HTTP/1.1" 404 3967
INFO 2024-03-12 14:04:14,375 autoreload 14544 12496 D:\Мои документы\Downloads\018\GB\Python.Django\project\lessons\task05\urls.py changed, reloading.
INFO 2024-03-12 14:04:14,816 autoreload 11616 5944 Watching for file changes with StatReloader
INFO 2024-03-12 14:04:15,989 views 11616 20372 The random number from 0 to 100 is 88
INFO 2024-03-12 14:04:15,999 basehttp 11616 20372 "GET /task05/random/10 HTTP/1.1" 200 1142
INFO 2024-03-12 14:04:19,322 views 11616 20372 The random number from 0 to 100 is 18
INFO 2024-03-12 14:04:19,324 basehttp 11616 20372 "GET /task05/random/10 HTTP/1.1" 200 1227
INFO 2024-03-12 14:04:19,905 views 11616 20372 The random number from 0 to 100 is 52
INFO 2024-03-12 14:04:19,907 basehttp 11616 20372 "GET /task05/random/10 HTTP/1.1" 200 1312
INFO 2024-03-12 14:04:20,364 views 11616 20372 The random number from 0 to 100 is 45
INFO 2024-03-12 14:04:20,365 basehttp 11616 20372 "GET /task05/random/10 HTTP/1.1" 200 1397
INFO 2024-03-12 14:04:20,772 views 11616 20372 The random number from 0 to 100 is 46
INFO 2024-03-12 14:04:20,774 basehttp 11616 20372 "GET /task05/random/10 HTTP/1.1" 200 1482
INFO 2024-03-12 14:04:24,647 views 11616 20372 Dice was tossed and gave number 5
INFO 2024-03-12 14:04:24,648 basehttp 11616 20372 "GET /task05/dice/ HTTP/1.1" 200 843
INFO 2024-03-12 14:04:27,172 views 11616 20372 Dice was tossed and gave number 4
INFO 2024-03-12 14:04:27,174 basehttp 11616 20372 "GET /task05/dice/10 HTTP/1.1" 200 1347
INFO 2024-03-12 14:04:30,156 views 11616 20372 Tails
INFO 2024-03-12 14:04:30,157 basehttp 11616 20372 "GET /task05/coin/ HTTP/1.1" 200 863
INFO 2024-03-12 14:04:32,548 views 11616 20372 Heads
INFO 2024-03-12 14:04:32,549 basehttp 11616 20372 "GET /task05/coin/10 HTTP/1.1" 200 1479
